apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        env:
          - name: MARIADB_ROOT_PASSWORD
            value: jhordycg
          - name: MARIADB_DATABASE
            value: h21_01bd 
        ports:
        - containerPort: 8080
