apiVersion: v1
kind: Service
metadata:
  name: payara
spec:
  type: NodePort
  ports:
  - name: admin
    port: 4848
    targetPort: 4848
    nodePort: 30048
  - name: web
    port: 8080
    nodePort: 30088
    targetPort: 8080
  selector:
    app: payara
