apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts-jdk11
        args:
          - "--argumentsRealm.passwd.demo=demo"
          - "--argumentsRealm.roles.demo=admin"
          - "--useJmx"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1500m"
      volumes:
      - name: jenkins-home
        emptyDir: { }
